version: '3.8'

services:
  rabbitmq:
    container_name: rabbitmq0
    image: rabbitmq:3.10.0-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - ./docker/rabbitmq/:/etc/rabbitmq/

  mysql:
    container_name: mysql0
    image: mariadb:10.8.2-rc-focal
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=expenses_registry
      - MYSQL_USER=expenses_registry_service
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret