spring:
  config:
    activate:
      on-profile: default, docker, local
  rabbitmq:
    host:
    port:
    username: expenses_registry
    password:
  datasource:
    url:
    username: expenses_registry
    password:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

management:
  info:
    java:
      enabled: true
    git:
      enabled: true
      mode: full
  endpoint:
    health:
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /manage
      path-mapping:
        health: /status
