spring:
  config:
    activate:
      on-profile: docker
  rabbitmq:
    host: host.docker.internal
    port: 5672
    username: expenses_registry
    password: secret
  datasource:
    url: jdbc:mariadb://host.docker.internal:3306/expenses_registry
    username: expenses_registry
    password: secret
